name: Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Get release version
        id: version
        run: echo "VER=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build program (PyInstaller)
        run: |
          pyinstaller --windowed --icon=icons/IHBS_icon.icns --distpath dist/ main.py -n "I Have Been Summoned"
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IHBS_macos
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ steps.version.outputs.VER }}
          files: dist/